name: Test

on:
  push:
    branches: ["dev"]

concurrency:
  group: unity-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
      name: Run tests
      runs-on: ubuntu-latest
      timeout-minutes: 30

      env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Unity tests
          uses: game-ci/unity-test-runner@v4
          with:
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            unityVersion: 6000.0.41f1
            projectPath: .


